### ISSUE TITLE
When installed with CLI, bin points to non-existent path

### ISSUE THREAD

**Issue by petersandor** [yeoman/generator-node#134] opened 2015-07-10 21:08 UTC
I just noticed that when I scaffold a new module with CLI by using `yo node --cli`, in `package.json` `bin` points to non-existent path (`"dist/cli.js"`).

As an example, I tried to link my new module with following result:

```
C:\Projects\testapp-node-cli
λ npm link
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path C:\Users\<user>\AppData\Roaming\npm\node_modules\testapp-node-cli\dist\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
```
And real dir structure:
```
...
├───lib
│       cli.js
│       index.js
│       
├───node_modules
├───test

```
However, if I run `yo node:cli` this issue doesn't happen. Not sure about the specifics, but I think it originates from here https://github.com/yeoman/generator-node/blob/master/generators/cli/index.js#L14

**Comment by SBoudrias** [comment] 2015-07-10 21:10
Ugh, yeah.

That generator really isn't great. It needs to define patterns for options and arguments in it's constructor. And it need to be smarter.

**Comment by arthurvr** [comment] 2015-07-10 21:12
I'll look into this. Try running `gulp babel` and `npm link` again?

> That generator really isn't great. It needs to define patterns for options and arguments in it's constructor. And it need to be smarter.

Yep. I totally agree.

**Comment by petersandor** [comment] 2015-07-10 21:19
That creates the `dist/cli.js`, also `npm link` works. But when I try to run the module, this happens:
```
C:\Projects\testapp-node-cli
λ gulp babel
[23:14:11] Using gulpfile C:\Projects\testapp-node-cli\gulpfile.js
[23:14:11] Starting 'babel'...
[23:14:11] Finished 'babel' after 175 ms

C:\Projects\testapp-node-cli
λ npm link
C:\Users\<user>\AppData\Roaming\npm\testapp-node-cli -> C:\Users\<user>\AppData\Roaming\npm\node_modules\testapp-node-cli\dist\cli.js
C:\Users\<user>\AppData\Roaming\npm\node_modules\testapp-node-cli -> C:\Projects\testapp-node-cli

C:\Projects\testapp-node-cli
λ testapp-node-cli
C:\Projects\testapp-node-cli\lib\index.js:2
export default {};
 ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projects\testapp-node-cli\dist\cli.js:15:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by arthurvr** [comment] 2015-07-10 21:24
> That creates the dist/cli.js, also npm link works.

Well, that's the expected behaviour. When using babel you of course have to compile your code first.

>  But when I try to run the module, this happens:

This is a bug not related to the CLI. The problem is that [our `main`](https://github.com/yeoman/generator-node/blob/28e44f23e43cf47f1b1f9d2b4bd324092222eb78/generators/app/index.js#L159) in the generated package.json points to `lib/index.js`, which is a problem when using babel as that's the source version not the compiled version.

**Comment by petersandor** [comment] 2015-07-10 21:36
I see, thanks for looking into this. :+1:

Also, I would like to mention that as a new user I was a bit confused by this issue since this wasn't happening when I ran `yo node:cli` (without `--no-babel`, doesn't it default to `true`?), it created only `lib/cli.js` and everything worked.

**Comment by SBoudrias** [comment] 2015-07-10 21:45
@petersandor This is not an issue on your side. This generator output is broke. We'll fix it.

**Comment by SBoudrias** [comment] 2015-07-15 06:19
@arthurvr You assigned yourself that ticket. I think it's working fine now, can you double check and close it if that's the case? Thanks :)

**Comment by arthurvr** [comment] 2015-07-17 20:33
Looks alright now. Nice work @SBoudrias :)

**Closed by arthurvr** 2015-07-17 20:33 UTC
Labels: bug

**Comment by hemanth** [comment] 2015-07-18 02:16
:+1:
