### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. When Babel is selected

### ISSUE THREAD

**Issue by stevemao** [yeoman/generator-node#118] opened 2015-06-22 23:54 UTC
Sorry I didn't raise this issue because I thought it might be just my local environment (I've been debugging and symlinking the project) but I got this by running `yo node`.

```
$ yo node
? Module Name: n
? Description:
? Project homepage url: n
? GitHub username or organization: n
? Author's Name: n
? Author's Email: n
? Author's Homepage: n
? Key your keywords (comma to split) n
? Send coverage reports to coveralls: No
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Queue.addListener (events.js:179:15)
    at Queue.once (events.js:204:8)
    at run (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:396:20)
    at composeWith (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:625:15)
    at module.exports.generators.Base.extend [as default] (/usr/local/lib/node_modules/generator-node/generators/app/index.js:213:12)
    at /usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:428:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at run (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:473:21)
    at composeWith (/usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:625:15)
    at module.exports.generators.Base.extend [as default] (/usr/local/lib/node_modules/generator-node/generators/app/index.js:213:12)
    at /usr/local/lib/node_modules/generator-node/node_modules/yeoman-generator/lib/base.js:428:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
? Which license do you want to use? Apache 2.0
```

It works fine nevertheless

I tried 
```
$ yo node --no-babel
```
and I don't get this warning anymore so I thought it might not just be my local env

Can you confirm? I'm not sure how this would happen. Many thanks.

**Comment by SBoudrias** [comment] 2015-06-22 23:58
This could happen if we have too many composed generators as they'll all listen for the same events.

You can increase the event listener limit for now. We should find a way internally to fix that issue.

**Comment by stevemao** [comment] 2015-06-23 00:01
Thanks for the quick response. For the reference: https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n

**Comment by robbbz** [comment] 2015-07-08 21:00
Shouldn't this be an issue in the generator repo?

**Comment by SBoudrias** [comment] 2015-07-08 21:33
Yes, duplicate of https://github.com/yeoman/generator/issues/778

**Closed by SBoudrias** 2015-07-08 21:33 UTC
